# %run

In [19]:
%run ./playML/hello.py

In [20]:
hello('imooc')

imooc hello world


In [ ]:
mymodule.FirstML.predict(1)

In [ ]:
from mymodule import FirstML
FirstML.predict(2)

# %timeit

In [ ]:
%timeit L = [i**2 for i in range(1000)]

In [ ]:
%timeit L = [i**2 for i in range(1000000)]

In [ ]:
%%timeit 
L = []
for n in range(1000):
    L.append(n**2)

In [ ]:
%time L = [i**2 for i in range(1000)]

In [ ]:
%%time 
L = []
for n in range(1000):
    L.append(n**2)

In [ ]:
import random
L = [random.random() for i in range(100000)]
%timeit L.sort()

# numpy.array基础

In [24]:
import numpy

In [25]:
numpy.__version__

'1.16.0'

In [26]:
import numpy as np

In [27]:
np.__version__

'1.16.0'

In [28]:
L = [i for i in range(10)]

In [29]:
L[5]

5

In [30]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
L[5] = 'Machine Learing'

In [32]:
L

[0, 1, 2, 3, 4, 'Machine Learing', 6, 7, 8, 9]

## np.array

In [33]:
import array
arr = array.array('i',[i for i in range(10)])

In [34]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5] = 100

In [36]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [37]:
nparr = np.array([i for i in range(10)])

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros(10).dtype

dtype('float64')

In [40]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.zeros(shape= (3,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
np.full(shape = (3,5),fill_value= 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

££ %time 

In [43]:
np.random.randint(4,8, size = 10)

array([7, 6, 7, 4, 7, 4, 6, 6, 5, 7])

In [44]:
np.random.randint(4,8, size = (3,5))

array([[7, 6, 7, 5, 6],
       [4, 5, 6, 7, 4],
       [7, 6, 4, 5, 6]])

## np.random.seed()

In [45]:
np.random.seed(10)

In [46]:
np.random.randint(4,8, size = (3,5))


array([[5, 5, 4, 7, 4],
       [5, 7, 4, 5, 5],
       [4, 5, 5, 6, 4]])

In [47]:
np.random.seed(10)
np.random.randint(4,8, size = (3,5))

array([[5, 5, 4, 7, 4],
       [5, 7, 4, 5, 5],
       [4, 5, 5, 6, 4]])

In [48]:
np.random.random(size = (3,5))

array([[0.26556613, 0.26360285, 0.15037787, 0.68381843, 0.81660184],
       [0.33607158, 0.89081653, 0.19812181, 0.03061665, 0.87761494],
       [0.72743551, 0.54088093, 0.13145815, 0.41366737, 0.77872881]])

In [49]:
np.random.normal(0,10,size = (3,5))

array([[-12.54241914,   3.31578554,  -3.08600486,  -1.53735485,
          6.78931195],
       [-19.13554213,  -9.42458056, -17.45542979, -10.20945267,
         -1.62069026],
       [ -6.579709  ,   4.22113062,   6.24023338,   5.01640096,
          8.41434727]])

In [50]:
np.random? 

SyntaxError: invalid syntax (<ipython-input-50-e8bc1feb66b0>, line 1)

# nump.array 的基本操作

In [51]:
import numpy as np

In [52]:
X = np.arange(15).reshape(3,5)

In [53]:
X.shape

(3, 5)

In [54]:
X.size

15

In [55]:
X.ndim

2

In [56]:
x = np.arange(10)

In [57]:
x[-1]

9

In [58]:
x[0]

0

In [59]:
X[-1]

array([10, 11, 12, 13, 14])

In [60]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
X[2,2]

12

In [62]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
x[0:5]

array([0, 1, 2, 3, 4])

In [64]:
x[:5]

array([0, 1, 2, 3, 4])

In [65]:
x[5:]

array([5, 6, 7, 8, 9])

In [66]:
x[::2]

array([0, 2, 4, 6, 8])

In [67]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
X[:2,:3]

In [ ]:
subx = X[:2,:3]

In [ ]:
subx[0,0] = 100

In [ ]:
X

In [ ]:
subx = X[:2,:3].copy()

In [ ]:
subx[0,0] = 0

In [ ]:
X

In [ ]:
B = x.reshape(2,5)
B

### 一维数组

In [ ]:
x

### 二维数组

In [ ]:
x.reshape(1,10)

In [ ]:
x.reshape(10,-1)

### 只需对应的行和对应的列就好

In [ ]:
x.reshape(-1,10)

In [ ]:
x.reshape(2,-1)

## 合并数组

In [68]:
y = np.array([3,2,1])
x = np.array([1,2,3])

In [69]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [70]:
z = np.array([666,666,666])

In [71]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [72]:
A = np.array([[1,2,3],
             [4,5,6]])

### np.concatenate 只能处理维度一样的数组

In [73]:
np.concatenate([A,A],axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [74]:
np.concatenate([A,A],axis =0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
A2 = np.concatenate([A,z.reshape(1,-1)],axis = 0)

In [76]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

###  np.vstack 能处理堆积行的数组(垂直方向)，np.hstack 能处理堆积列的数组

In [77]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

### np.split() 分割操作

In [78]:
x1,x2,x3 = np.split(x,[3,7])

In [79]:
x1

array([1, 2, 3])

In [80]:
x2

array([], dtype=int32)

In [81]:
x3

array([], dtype=int32)

In [82]:
A = np.arange(16).reshape((4,4))

In [83]:
A1,A2 = np.split(A,[2])

In [84]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
A1,A2 = np.split(A,[2],axis = 1)

In [87]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [88]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [89]:
upper ,lower = np.vsplit(A,[2])

In [90]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [91]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
left ,right = np.hsplit(A,[2])

In [93]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [94]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
data  =  np.arange(16).reshape((4,4))

In [97]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
x, y  = np.hsplit(data,[-1])

In [99]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [100]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [101]:
y[:,0]

array([ 3,  7, 11, 15])

# numpy.array 的运算  与list的计算时间是不在一个级别的

In [102]:
n = 1000000
L = [ i for i in range(n)]

In [103]:
%%time
A = []
for e in L:
    A.append(e*2)

Wall time: 201 ms


In [104]:
L = np.arange(n)
A = [e*2 for e in L]

In [105]:
%%time
A= L*2
A

Wall time: 22.1 ms


In [106]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [107]:
L = np.arange(10)

### Universal Function

In [108]:
X = np.arange(1,16).reshape((3,5))

In [109]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [110]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [111]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [112]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:

X/2

In [ ]:
1/X

In [ ]:
X%2

In [ ]:
X//2

In [ ]:
np.log(X)

In [ ]:
np.log10(X)

### 矩阵计算

In [113]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [114]:
B = np.full((2,2),fill_value = 10)
B 

array([[10, 10],
       [10, 10]])

In [115]:
A+B

array([[10, 11],
       [12, 13]])

In [116]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [117]:
A*B

array([[ 0, 10],
       [20, 30]])

In [118]:
A/B

array([[0. , 0.1],
       [0.2, 0.3]])

In [119]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [120]:
v = np.array([1,2])

In [121]:
v

array([1, 2])

In [122]:
A

array([[0, 1],
       [2, 3]])

In [123]:
v+A

array([[1, 3],
       [3, 5]])

In [ ]:
np.vstack([v]*A.shape[0]) #堆叠的矩阵

In [ ]:
A

In [ ]:
v*2

In [ ]:
np.tile(v,(2,1))

In [ ]:
np.tile(v,(2,1))+A

### 矩阵的逆

In [ ]:
A

In [ ]:
np.linalg.inv(A)

In [ ]:
inA = np.linalg.inv(A)

In [ ]:
inA.dot(A)

In [ ]:
A.dot(inA)

In [ ]:
X = np.arange(16).reshape((2,8))

In [ ]:
np.linalg.pinv(X)

In [ ]:
inX = np.linalg.pinv(X)

In [ ]:
X .dot(inX)

### 聚合操作

In [ ]:
L = np.random.random(100)

In [ ]:
L

In [ ]:
sum(L)

In [ ]:
np.sum(L)

In [ ]:
big_array = np.random.random(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

In [ ]:
np.max(big_array)

In [ ]:
np.min(big_array)

In [ ]:
X = np.arange(16).reshape(4,-1)


In [ ]:
X

In [ ]:
np.sum(X)

### axis是沿着行进行计算

In [ ]:
np.sum(X,axis = 0)

In [ ]:
np.sum(X,axis = 0)

In [ ]:
np.prod(X+1)

In [ ]:
np.median(X)

In [ ]:
v = np.array([1,1,2,2,10])

In [ ]:
np.max(big_array)

In [ ]:
for percent in [0,25,50,100]:
   print(np.percentile(big_array,q = percent))

In [ ]:
np.var(big_array)

In [ ]:
np.std(big_array)

In [ ]:
np.sqrt(np.var(big_array))

In [ ]:
x = np.random.normal(0,1,size = 1000)

In [ ]:
x.mean()

In [ ]:
x.std()

### 索引操作

In [ ]:
np.min(big_array)

In [ ]:
np.argmin(big_array)

In [ ]:
big_array[35348]

### 排序和使用索引

In [124]:
 x = np.arange(16)

In [125]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
np.random.shuffle(x)

In [127]:
x

array([ 1,  7, 14, 12,  9,  4,  0,  3, 10,  5, 11, 15, 13,  8,  2,  6])

In [128]:
x.sort()

In [129]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [130]:
X = np.random.randint(10,size = (4,4))

In [131]:
X

array([[9, 1, 8, 9],
       [1, 2, 8, 9],
       [9, 5, 0, 2],
       [7, 3, 0, 4]])

In [132]:
np.sort(X)

array([[1, 8, 9, 9],
       [1, 2, 8, 9],
       [0, 2, 5, 9],
       [0, 3, 4, 7]])

In [133]:
np.sort(X,axis = 0)

array([[1, 1, 0, 2],
       [7, 2, 0, 4],
       [9, 3, 8, 9],
       [9, 5, 8, 9]])

In [134]:
np.sort(X,axis = 1)

array([[1, 8, 9, 9],
       [1, 2, 8, 9],
       [0, 2, 5, 9],
       [0, 3, 4, 7]])

In [135]:
x 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [136]:
np.random.shuffle(x)

In [137]:
x

array([ 7, 12,  9,  4,  6,  8, 11, 10, 14,  5, 15,  1, 13,  3,  0,  2])

In [138]:
np.argsort(x)

array([14, 11, 15, 13,  3,  9,  4,  0,  5,  2,  7,  6,  1, 12,  8, 10],
      dtype=int64)

In [139]:
np.partition(x,3) # 标定点进行切片处理

array([ 0,  1,  2,  3,  4,  6,  5,  7, 14, 12, 15, 11, 13,  8,  9, 10])

In [140]:
np.argpartition(x,3) # 标定点进行切片处理

array([14, 11, 15, 13,  3,  4,  9,  0,  8,  1, 10,  6, 12,  5,  2,  7],
      dtype=int64)

In [141]:
X

array([[9, 1, 8, 9],
       [1, 2, 8, 9],
       [9, 5, 0, 2],
       [7, 3, 0, 4]])

In [142]:
np.argsort(X,axis = 1)

array([[1, 2, 0, 3],
       [0, 1, 2, 3],
       [2, 3, 1, 0],
       [2, 1, 3, 0]], dtype=int64)

In [143]:
np.argpartition(X,2,axis =1)

array([[1, 2, 0, 3],
       [0, 1, 2, 3],
       [2, 3, 1, 0],
       [2, 1, 3, 0]], dtype=int64)

### Fancy Indexing

In [144]:
x = np.arange(16)

In [145]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [146]:
x[3]

3

In [147]:
x[3:9:2]

array([3, 5, 7])

In [148]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [149]:
ind = [3,5,8]
x[ind]
x[[3,5,8]]

array([3, 5, 8])

In [150]:
x[ind]

array([3, 5, 8])

In [151]:
ind = np.array([[0,1],[2,3]])

In [152]:
x[ind]

array([[0, 1],
       [2, 3]])

In [153]:
X = x.reshape(4,-1)

In [154]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [155]:
row = np.array([0,1,2])
col = np.array([1,2,3])

In [156]:
X[row,col]

array([ 1,  6, 11])

In [157]:
X[0,col]

array([1, 2, 3])

In [158]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [159]:
col = [True,False,True,True]

In [160]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [161]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [162]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [163]:
x[x<3]

array([0, 1, 2])

In [164]:
x!= 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [165]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [166]:
2*4 ==24-2*x

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False])

In [167]:
np.count_nonzero(x<=3)

4

In [ ]:
np.any(x==0)

In [ ]:
np.any(x<0)

In [ ]:
np.all(x>=0)

In [ ]:
X

In [ ]:
np.sum(X%2==0,axis =1)

In [ ]:
np.sum(X%2==0 ,axis = 0)

In [ ]:
np.all(X>0,axis =0)

In [ ]:
np.all(X>0,axis =1)

In [ ]:
x

In [ ]:
np.sum((x>3)&(x<6)) ## 位运算符号

In [ ]:
np.sum((x>3)|(x<10))

In [ ]:
np.sum(~(x==0))

# matplotlib 基础操作

In [11]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [168]:
x = np.linspace(1,10,100)

In [ ]:
y = np.sin(x)
y1 = np.cos(x)

In [ ]:
plt.plot(x,y,linestyle ='--',label = 'sinx')
plt.plot(x,y1,color = 'red',linestyle ='-',label = 'cosx')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()

In [ ]:
x = np.random.normal(0,1,1000)
y = np.random.normal(0,1,1000)
plt.scatter(x,y,alpha= 0.5)

# 读取数据和简单的数据处理

In [ ]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()

In [ ]:
iris.keys()

In [ ]:
(iris.data)

In [ ]:
iris.target.shape

In [ ]:
iris.target_names

In [ ]:
X = iris.data[:,:2]

In [ ]:
X

In [ ]:
iris.feature_names

In [ ]:
iris.target

In [ ]:
y = iris.target

In [ ]:
plt.scatter(X[y==0,0],X[y==0,1],color = 'red',marker= ='o')
plt.scatter(X[y==1,0],X[y==1,1],color = 'blue',marker= ='+')
plt.scatter(X[y==2,0],X[y==2,1],color = 'green'，marker= ='*')

In [ ]:
X = iris.data[:,2:]
plt.scatter(X[y==0,0],X[y==0,1],color = 'red',marker ='o')
plt.scatter(X[y==1,0],X[y==1,1],color = 'blue',marker ='+')
plt.scatter(X[y==2,0],X[y==2,1],color = 'green',marker ='*')